services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    networks:
      - cinema-network
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db_data:/var/lib/mysql

  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    container_name: cinema-server
    restart: always
    networks:
      - cinema-network
    env_file:
      - .env
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./server:/app
      - server_node_modules:/app/node_modules
    depends_on:
      - mysql

  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    container_name: cinema-client
    restart: always
    networks:
      - cinema-network
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules
    depends_on:
      - server

networks:
  cinema-network:
    driver: bridge

volumes:
  db_data:
  client_node_modules:
  server_node_modules:
